### PR TITLE
update Farsi translations

### PR DESCRIPTION
**Pull request by mhdr**
Gantt_EmptyRecord
PivotView_EmptyRecordsMessage
Grid_EmptyRecord
Pager_CurrentPageInfo

### CODE REVIEW

**Comment by Lingala-Joshna** [comment]
@mhdr, We have validated and we couldn't approve this change. You can modify and use in your application level

**Comment by mhdr** [comment]
@Lingala-Joshna I think you should revise your Farsi translations, obviously they are machine translated and most of them are not correct.

**Comment by syncsiva** [comment]
@mhdr 

we have validated the changes. Your have proposed to changed **records to files** and **pages to page**. Can you please check below details? 


Syncfusion   Key | English | Farsi   Language in Resource file | Proposed   in PR #77 | PR #77  proposed strings in Google translate | PR #77 proposed   strings in Microsoft Binge translate
-- | -- | -- | -- | -- | --
Gantt_EmptyRecord | No   records to display | هیچ پرونده برای نمایش   نیست | هیچ پرونده‌ای برای   نمایش نیست | There   are no files to display | No files   to display
PivotView_EmptyRecordsMessage | No   records to display | هیچ پرونده برای نمایش   نیست | هیچ پرونده‌ای برای نمایش   نیست | There   are no files to display | No files   to display
Grid_EmptyRecord | No   records to display | هیچ پرونده برای نمایش   نیست | هیچ پرونده‌ای برای   نمایش نیست | There   are no files to display | No files   to display
Pager_CurrentPageInfo | {0}   of {1} pages | {0} از {1}   صفحات | {0} از {1} صفحه | {0}   of {1} pages | {0} of   page {1}

**Comment by mhdr** [comment]
@syncsiva 
I confirm changing from **pages** to **page** because we use singular form in this case in Farsi.
The other one is not changing from records to files, it's adding "ای" to the word "پرونده‌".
You can find more about different kinds of "ای" in Farsi here :
https://liar.ui.ac.ir/article_19719.html
So I confirm adding **"ای"** to the word **"پرونده‌"**.
In addition, the translation of record to "پرونده" is not precisely correct, but it's a different story.

**Comment by syncsiva** [comment]
@mhdr We have validated and merged the changes in the below PR
https://github.com/syncfusion/blazor-locale/pull/86

**Pull request closed without merging**
